services:
  typesense:
    image: typesense/typesense:28.0
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    environment:
      - TYPESENSE_API_KEY=your_api_key_here
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_ENABLE_CORS=true
